ALTER TABLE "Game" ADD COLUMN "gameplayImages" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN "tags" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN "externalRating" DOUBLE PRECISION;
ALTER TABLE "Game" ADD COLUMN "externalRatingCount" INTEGER;
ALTER TABLE "Game" ADD COLUMN "externalRatingProvider" TEXT;
ALTER TABLE "Game" ADD COLUMN "externalRatingType" TEXT;
ALTER TABLE "Game" ADD COLUMN "externalRatingUpdatedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "usernameNormalized" TEXT;
UPDATE "User" SET "usernameNormalized"=LOWER(TRIM("username"));
ALTER TABLE "User" ALTER COLUMN "usernameNormalized" SET NOT NULL;
CREATE UNIQUE INDEX "User_usernameNormalized_key" ON "User"("usernameNormalized");
ALTER TABLE "User" DROP COLUMN "displayName";
CREATE TABLE "GameMedia"("id" TEXT PRIMARY KEY,"gameId" TEXT NOT NULL REFERENCES "Game"("id") ON DELETE CASCADE,"type" TEXT NOT NULL,"path" TEXT NOT NULL,"source" TEXT NOT NULL,"sourceExternalId" TEXT,"sourceFilename" TEXT,"width" INTEGER NOT NULL,"height" INTEGER NOT NULL,"fileSize" INTEGER NOT NULL,"sortOrder" INTEGER NOT NULL DEFAULT 1,"platformVerified" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "GameMedia_gameId_type_sortOrder_key" ON "GameMedia"("gameId","type","sortOrder");
CREATE TABLE "RegistrationChallenge"("id" TEXT PRIMARY KEY,"tokenHash" TEXT UNIQUE NOT NULL,"answerHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "RegistrationChallenge_expiresAt_idx" ON "RegistrationChallenge"("expiresAt");
CREATE TABLE "RegistrationAttempt"("id" TEXT PRIMARY KEY,"ipHash" TEXT NOT NULL,"emailNormalized" TEXT,"usernameNormalized" TEXT,"success" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "RegistrationAttempt_ipHash_createdAt_idx" ON "RegistrationAttempt"("ipHash","createdAt");
CREATE INDEX "RegistrationAttempt_emailNormalized_createdAt_idx" ON "RegistrationAttempt"("emailNormalized","createdAt");
CREATE INDEX "RegistrationAttempt_usernameNormalized_createdAt_idx" ON "RegistrationAttempt"("usernameNormalized","createdAt");
