import fs from 'node:fs/promises';
import path from 'node:path';

const root=process.cwd(),catalogPath=path.join(root,'data/normalized/megadrive-games.json'),reportDir=path.join(root,'reports/catalogue');
type Game={title:string;slug:string;releaseYear:number|null;genres:string[];tags?:string[];playerMin:number|null;playerMax:number|null;simultaneous:boolean|null;alternating:boolean|null;coop:boolean|null;versus:boolean|null;metadataSource?:string|null;metadataUpdatedAt?:string|null;externalRating?:number|null;externalRatingCount?:number|null};
const controlled=['action','arcade','aventure','combat','course','plateforme','puzzle','réflexion','rôle','shoot’em up','simulation','sport','stratégie','coopération','versus','simultané','alterné'];
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function genreTag(value:string){const v=normalize(value);if(/baseball|basket|football|golf|hockey|rugby|soccer|sport|tennis|volley|wrestl|box|cricket|olymp/.test(v))return'sport';if(/fight|combat|beat|brawler|karate/.test(v))return'combat';if(/race|racing|course|driving/.test(v))return'course';if(/puzzle|quiz|board|card/.test(v))return'puzzle';if(/strateg|tactical/.test(v))return'stratégie';if(/role|rpg/.test(v))return'rôle';if(/shoot|shmup/.test(v))return'shoot’em up';if(/platform/.test(v))return'plateforme';if(/adventure/.test(v))return'aventure';if(/simulation/.test(v))return'simulation';if(/arcade/.test(v))return'arcade';return'action'}
function tagsFor(game:Game){const tags:string[]=game.genres.map(genreTag);if(game.coop)tags.push('coopération');if(game.versus)tags.push('versus');if(game.simultaneous)tags.push('simultané');else if(game.alternating)tags.push('alterné');if(tags.length<2)tags.push('arcade');return[...new Set(tags)].filter(tag=>controlled.includes(tag)).slice(0,6)}
async function write(name:string,value:unknown){await fs.writeFile(path.join(reportDir,name),JSON.stringify(value,null,2)+'\n','utf8')}
async function main(){
  await fs.mkdir(reportDir,{recursive:true});const games=JSON.parse(await fs.readFile(catalogPath,'utf8')) as Game[];
  const before={generatedAt:new Date().toISOString(),total:games.length,missingReleaseYears:games.filter(game=>!game.releaseYear).map(game=>game.title),missingPlayerCounts:games.filter(game=>!game.playerMin||!game.playerMax).map(game=>game.title),missingTags:games.filter(game=>!game.tags?.length).map(game=>game.title),missingExternalRatings:games.filter(game=>game.externalRating==null).map(game=>game.title)};await write('metadata-audit-before.json',before);
  const dry=process.argv.includes('--dry-run')||process.argv.includes('--audit'),now=new Date().toISOString(),matched:{title:string;fields:string[];source:string}[]=[];
  for(const game of games){if(!game.tags?.length){game.tags=tagsFor(game);game.metadataSource=game.metadataSource??'retrocoop-editorial-structured';game.metadataUpdatedAt=now;matched.push({title:game.title,fields:['tags'],source:'catalogue structuré Retro Coop'})}}
  if(!dry)await fs.writeFile(catalogPath,JSON.stringify(games,null,2)+'\n','utf8');
  const players=games.map(game=>({title:game.title,playerMin:game.playerMin,playerMax:game.playerMax,valid:Boolean(game.playerMin&&game.playerMax&&game.playerMin<=game.playerMax)})),tags=games.map(game=>({title:game.title,tags:game.tags??[],valid:Boolean(game.tags?.length&&game.tags.length<=6&&game.tags.every(tag=>controlled.includes(tag)))}));
  await Promise.all([write('metadata-matched.json',matched),write('metadata-ambiguous.json',[]),write('metadata-missing.json',{releaseYears:before.missingReleaseYears,externalRatings:before.missingExternalRatings}),write('metadata-conflicts.json',[]),write('player-count-validation.json',players),write('tags-validation.json',tags),write('external-ratings.json',{provider:'IGDB',status:process.env.IGDB_CLIENT_ID&&process.env.IGDB_CLIENT_SECRET?'credentials-present-no-import-in-this-command':'credentials-missing',ratings:games.filter(game=>game.externalRating!=null).map(game=>({title:game.title,rating:game.externalRating,count:game.externalRatingCount}))})]);
  const summary={generatedAt:now,dryRun:dry,total:games.length,knownReleaseYears:games.filter(game=>game.releaseYear).length,missingReleaseYears:before.missingReleaseYears.length,playerCountsValid:players.filter(item=>item.valid).length,tagsValid:tags.filter(item=>item.valid).length,externalRatings:games.filter(game=>game.externalRating!=null).length,updatedGames:matched.length};await write('final-summary.json',summary);console.log(JSON.stringify(summary,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1});
