import fs from 'node:fs/promises';
import path from 'node:path';
import {PrismaClient,VerificationStatus} from '@prisma/client';
const prisma=new PrismaClient();
type Media={path:string;source:string;sourceFilename?:string;width:number;height:number;fileSize:number;sortOrder:number;platformVerified:boolean;importedAt?:string};
type Game={title:string;sortTitle:string;slug:string;aliases:string[];region:string|null;releaseYear:number|null;description:string|null;descriptionSourceType?:string|null;descriptionSourceUrl?:string|null;descriptionSourceLanguage?:string|null;descriptionAdaptedToFrench?:boolean;descriptionVerifiedPlatform?:string|null;metadataSource?:string|null;metadataExternalId?:string|null;metadataUpdatedAt?:string|null;coverUrl?:string|null;coverSource?:string|null;coverAttribution?:string|null;gameplayImages?:Media[];externalRating?:number|null;externalRatingCount?:number|null;externalRatingProvider?:string|null;externalRatingType?:string|null;externalRatingUpdatedAt?:string|null;genres:string[];tags?:string[];playerMin:number|null;playerMax:number|null;simultaneous:boolean|null;alternating:boolean|null;coop:boolean|null;versus:boolean|null;dropIn:boolean|null;splitScreen:boolean|null;multitap:boolean|null;verificationStatus:VerificationStatus};

async function main(){
  const games=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/normalized/megadrive-games.json'),'utf8')) as Game[];
  const platform=await prisma.platform.upsert({where:{slug:'megadrive'},update:{name:'Mega Drive',manufacturer:'Sega'},create:{slug:'megadrive',name:'Mega Drive',manufacturer:'Sega'}});
  await prisma.game.deleteMany({where:{platformId:platform.id,slug:{notIn:games.map(game=>game.slug)}}});
  for(const game of games){
    const data={title:game.title,sortTitle:game.sortTitle,aliases:game.aliases??[],region:game.region,releaseYear:game.releaseYear,description:game.description,descriptionSourceType:game.descriptionSourceType??null,descriptionSourceUrl:game.descriptionSourceUrl??null,descriptionSourceLanguage:game.descriptionSourceLanguage??null,descriptionAdaptedToFrench:game.descriptionAdaptedToFrench??false,descriptionVerifiedPlatform:game.descriptionVerifiedPlatform??null,metadataSource:game.metadataSource??null,metadataExternalId:game.metadataExternalId??null,metadataUpdatedAt:game.metadataUpdatedAt?new Date(game.metadataUpdatedAt):null,coverUrl:game.coverUrl??null,coverSource:game.coverSource??null,coverAttribution:game.coverAttribution??null,gameplayImages:game.gameplayImages??[],externalRating:game.externalRating??null,externalRatingCount:game.externalRatingCount??null,externalRatingProvider:game.externalRatingProvider??null,externalRatingType:game.externalRatingType??null,externalRatingUpdatedAt:game.externalRatingUpdatedAt?new Date(game.externalRatingUpdatedAt):null,genres:game.genres??[],tags:game.tags??[],playerMin:game.playerMin,playerMax:game.playerMax,simultaneous:game.simultaneous,alternating:game.alternating,coop:game.coop,versus:game.versus,dropIn:game.dropIn,splitScreen:game.splitScreen,multitap:game.multitap,verificationStatus:game.verificationStatus,published:true};
    const record=await prisma.game.upsert({where:{platformId_slug:{platformId:platform.id,slug:game.slug}},update:data,create:{platformId:platform.id,slug:game.slug,...data}});
    await prisma.gameMedia.deleteMany({where:{gameId:record.id,type:'gameplay'}});
    if(game.gameplayImages?.length)await prisma.gameMedia.createMany({data:game.gameplayImages.slice(0,3).map(media=>({gameId:record.id,type:'gameplay',path:media.path,source:media.source,sourceUrl:`https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Snaps/${encodeURIComponent(media.sourceFilename??'')}`,sourceFilename:media.sourceFilename,width:media.width,height:media.height,fileSize:media.fileSize,sortOrder:media.sortOrder,platformVerified:media.platformVerified,verifiedPlatform:'Mega Drive',verifiedTitle:game.title,commercialCover:false,prototypeVisual:false,importedAt:media.importedAt?new Date(media.importedAt):new Date()}))});
  }
  console.log(`Base synchronisée : ${games.length} jeux.`);
}
main().finally(()=>prisma.$disconnect());
