'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
type Message={id:string;content:string;deleted:boolean;createdAt:string;suspicious:boolean;session:{id:string;title:string};author:{id:string;username:string;chatMutedUntil:string|null};reports:Array<{id:string;reason:string}>};
export default function ChatModeration(){
  const [messages,setMessages]=useState<Message[]>([]),[query,setQuery]=useState(''),[stats,setStats]=useState({openReports:0,rateLimitEvents24h:0}),[error,setError]=useState('');
  async function load(value=''){const response=await fetch(`/api/admin/moderation/chat?query=${encodeURIComponent(value)}`,{cache:'no-store'});if(!response.ok){setError((await response.json()).error);return}const result=await response.json();setMessages(result.messages);setStats(result)}
  useEffect(()=>{queueMicrotask(()=>void load())},[]);
  async function remove(id:string){const reason=prompt('Raison de la suppression','Contenu contraire aux règles');if(reason===null)return;await fetch(`/api/admin/moderation/messages/${id}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});void load(query)}
  async function mute(userId:string,active:boolean){await fetch(`/api/admin/moderation/users/${userId}/mute`,active?{method:'DELETE'}:{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({minutes:60,reason:'Modération du chat'})});void load(query)}
  function search(event:FormEvent){event.preventDefault();void load(query)}
  return <><form className="moderation-search" onSubmit={search}><label>Rechercher une session, un pseudo ou un message<input value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="btn">Rechercher</button></form><p>{stats.openReports} signalement(s) ouvert(s) · {stats.rateLimitEvents24h} limitation(s) de débit sur 24 h</p>{error&&<p className="form-error">{error}</p>}<div className="moderation-list">{messages.map(message=><article key={message.id}><div><Link href={`/sessions/${message.session.id}`}><strong>{message.session.title}</strong></Link><span>{message.author.username} · {new Date(message.createdAt).toLocaleString('fr-FR')}</span></div><p>{message.content}</p>{message.suspicious&&<span className="badge warning">Lien suspect</span>}{message.reports.map(report=><span className="badge" key={report.id}>Signalé : {report.reason}</span>)}<div><button type="button" className="danger-link" disabled={message.deleted} onClick={()=>remove(message.id)}>Supprimer</button><button type="button" className="danger-link" onClick={()=>mute(message.author.id,Boolean(message.author.chatMutedUntil))}>{message.author.chatMutedUntil?'Réactiver':'Suspendre 1 h'}</button></div></article>)}</div></>;
}
