'use client';
import {FormEvent,KeyboardEvent,useCallback,useEffect,useRef,useState} from 'react';
type Message={id:string;content:string;createdAt:string;deleted:boolean;author:{id:string;username:string};isOwnMessage:boolean;suspicious:boolean};
export default function SessionChat({sessionId,readOnly}:{sessionId:string;readOnly:boolean}){
  const [messages,setMessages]=useState<Message[]>([]),[error,setError]=useState(''),[sending,setSending]=useState(false),[newBelow,setNewBelow]=useState(false),box=useRef<HTMLDivElement>(null),form=useRef<HTMLFormElement>(null),nearBottom=useRef(true);
  const scrollBottom=()=>{box.current?.scrollTo({top:box.current.scrollHeight,behavior:'smooth'});setNewBelow(false)};
  const load=useCallback(async()=>{const response=await fetch(`/api/sessions/${sessionId}/messages`,{cache:'no-store',credentials:'include'});if(!response.ok)return;const result=await response.json() as {messages:Message[]};setMessages(previous=>{if(result.messages.length>previous.length&&!nearBottom.current)setNewBelow(true);return result.messages});if(nearBottom.current)requestAnimationFrame(scrollBottom)},[sessionId]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(sending||readOnly)return;const content=String(new FormData(event.currentTarget).get('content')??'');setSending(true);setError('');const response=await fetch(`/api/sessions/${sessionId}/messages`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,clientRequestId:crypto.randomUUID()})}),result=await response.json();setSending(false);if(!response.ok){setError(result.error??'Envoi impossible.');return}event.currentTarget.reset();setMessages(items=>[...items,result.message]);nearBottom.current=true;requestAnimationFrame(scrollBottom)}
  function keyDown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();form.current?.requestSubmit()}}
  async function report(messageId:string){const choice=prompt('Motif : Spam, Insulte, Contenu inapproprié ou Autre','Spam');if(!choice)return;const normalized=choice.toLocaleLowerCase('fr'),reason=normalized.startsWith('insulte')?'INSULTE':normalized.startsWith('contenu')?'INAPPROPRIE':normalized.startsWith('autre')?'AUTRE':'SPAM';const response=await fetch(`/api/sessions/${sessionId}/messages/${messageId}/report`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});setError(response.ok?'Message signalé à la modération.':(await response.json()).error??'Signalement impossible.')}
  return <section className="session-chat" aria-labelledby="chat-title"><div className="chat-heading"><div><h2 id="chat-title">Conversation</h2><p>Réservée à l’organisateur et aux participants actifs.</p></div>{newBelow&&<button type="button" className="btn secondary" onClick={scrollBottom}>Nouveaux messages</button>}</div><div className="chat-messages" ref={box} onScroll={event=>{const element=event.currentTarget;nearBottom.current=element.scrollHeight-element.scrollTop-element.clientHeight<80;if(nearBottom.current)setNewBelow(false)}} aria-live="polite">{messages.length?messages.map(message=><article className={`chat-bubble ${message.isOwnMessage?'own':''}`} key={message.id}><header><strong>{message.isOwnMessage?'Vous':message.author.username}</strong><time dateTime={message.createdAt}>{new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(new Date(message.createdAt))}</time></header><p className={message.deleted?'deleted':''}>{message.content}</p>{!message.isOwnMessage&&!message.deleted&&<button className="report-link" type="button" onClick={()=>report(message.id)}>Signaler</button>}</article>):<p className="empty-chat">Aucun message. Lancez la conversation.</p>}</div>{error&&<p className={error.startsWith('Message signalé')?'form-success':'form-error'} role="status">{error}</p>}{readOnly?<p className="empty-state">Cette conversation est désormais en lecture seule.</p>:<form ref={form} className="chat-form" onSubmit={submit}><label htmlFor="chat-content">Votre message</label><textarea id="chat-content" name="content" rows={3} maxLength={500} onKeyDown={keyDown} placeholder="Entrée pour envoyer, Maj + Entrée pour aller à la ligne" required/><div><small>500 caractères maximum · texte brut</small><button className="btn" disabled={sending}>{sending?'Envoi…':'Envoyer'}</button></div></form>}</section>;
}
