import {expect,test,type BrowserContext,type Page} from '@playwright/test';
import {PrismaClient} from '@prisma/client';
test.describe.configure({mode:'serial',timeout:120_000});
async function register(context:BrowserContext,prefix:string){const page=await context.newPage(),stamp=`${Date.now()}${Math.floor(Math.random()*10000)}`,email=`${prefix}-${stamp}@retrocoop.test`,username=`${prefix}${stamp}`.slice(0,28),password='Test-pass-2026!';await page.goto('/inscription');const question=await page.getByText(/Combien font \d+ \+ \d+/).textContent(),values=question!.match(/\d+/g)!.map(Number);await page.getByLabel('Email').fill(email);await page.getByLabel('Pseudo').fill(username);await page.getByLabel('Mot de passe').fill(password);await page.getByLabel(/Combien font/).fill(String(values[0]+values[1]));await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page).toHaveURL(/\/catalogue\?notice=registered/);return{page,email,username}}
async function createSession(page:Page){await page.goto('/sessions/nouvelle');await page.getByLabel('Jeu').pressSequentially('Streets of Rage 3');await page.getByRole('option',{name:/Streets of Rage 3/}).click();const future=new Date(Date.now()+3*86400000).toISOString().slice(0,10);await page.getByLabel('Date',{exact:true}).fill(future);await page.getByLabel('Heure',{exact:true}).fill('20:00');await page.getByLabel('Nombre maximum de joueurs').fill('4');const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/sessions')&&response.request().method()==='POST');await page.getByRole('button',{name:'Publier la session'}).click();const response=await responsePromise,body=await response.json();expect(response.status()).toBe(201);await expect(page).toHaveURL(new RegExp(`/sessions/${body.session.id}`));return body.session.id as string}

test('médias, confidentialité, chat, flood, notifications et modération à trois comptes',async({browser})=>{
  const prisma=new PrismaClient(),ownerContext=await browser.newContext(),participantContext=await browser.newContext(),outsiderContext=await browser.newContext(),owner=await register(ownerContext,'host'),participant=await register(participantContext,'player'),outsider=await register(outsiderContext,'visitor');let sessionId='';
  try{
    await prisma.user.update({where:{email:owner.email},data:{role:'ADMIN'}});sessionId=await createSession(owner.page);
    await owner.page.goto('/sessions');const card=owner.page.locator(`[data-session-id="${sessionId}"]`),cardCover=card.getByRole('img',{name:/Jaquette de Streets of Rage 3 sur Mega Drive/});await expect(cardCover).toBeVisible();expect(await cardCover.getAttribute('src')).toMatch(/streets-of-rage-3-[a-f0-9]{8}\.webp$/);expect((await owner.page.request.get((await cardCover.getAttribute('src'))!)).ok()).toBeTruthy();
    await owner.page.goto(`/sessions/${sessionId}`);const detailCover=owner.page.getByRole('img',{name:'Jaquette de Streets of Rage 3 sur Mega Drive'});await expect(detailCover).toBeVisible();expect((await owner.page.request.get((await detailCover.getAttribute('src'))!)).ok()).toBeTruthy();await expect(owner.page.getByRole('heading',{name:'Conversation'})).toBeVisible();
    const publicResponse=await outsider.page.request.get(`/api/sessions/${sessionId}`),publicText=await publicResponse.text();expect(publicText).not.toContain(owner.email);expect(publicText).not.toContain(participant.email);expect(publicText).not.toMatch(/"(?:email|password|passwordHash|authSecret)"\s*:/);
    await outsider.page.goto(`/sessions/${sessionId}`);await expect(outsider.page.getByRole('heading',{name:'Conversation'})).toHaveCount(0);expect((await outsider.page.request.get(`/api/sessions/${sessionId}/messages`)).status()).toBe(403);
    const joined=await participant.page.request.post(`/api/sessions/${sessionId}/join`);expect(joined.status()).toBe(201);expect((await participant.page.request.post(`/api/sessions/${sessionId}/join`)).status()).toBe(409);const participantUser=await prisma.user.findUniqueOrThrow({where:{email:participant.email}});await participant.page.goto(`/sessions/${sessionId}`);await expect(participant.page.getByRole('heading',{name:'Conversation'})).toBeVisible();
    const notifications=await owner.page.request.get('/api/notifications'),notificationBody=await notifications.json();expect(notificationBody.unreadCount).toBe(1);expect(await prisma.notification.count({where:{sessionId,actorId:participantUser.id}})).toBe(1);expect(JSON.stringify(notificationBody)).not.toContain(participant.email);expect(notificationBody.notifications[0].body).toContain(participant.username);const storedNotification=await prisma.notification.findFirstOrThrow({where:{sessionId,actor:{email:participant.email}}});expect(['DISABLED','PREFERENCE_DISABLED','FAILED','SENT']).toContain(storedNotification.emailStatus);
    await owner.page.reload();await expect(owner.page.getByRole('button',{name:/1 notification non lue/})).toBeVisible();
    const first=await participant.page.request.post(`/api/sessions/${sessionId}/messages`,{data:{content:'Bonjour tout le monde',clientRequestId:crypto.randomUUID()}});expect(first.status()).toBe(201);const firstMessage=(await first.json()).message;const ownerMessages=await owner.page.request.get(`/api/sessions/${sessionId}/messages`),ownerBody=await ownerMessages.json();expect(ownerBody.messages.at(-1).author.username).toBe(participant.username);expect(JSON.stringify(ownerBody)).not.toContain(participant.email);
    const answer=await owner.page.request.post(`/api/sessions/${sessionId}/messages`,{data:{content:'Bienvenue dans la session',clientRequestId:crypto.randomUUID()}});expect(answer.status()).toBe(201);const answerMessage=(await answer.json()).message;expect((await participant.page.request.post(`/api/sessions/${sessionId}/messages/${answerMessage.id}/report`,{data:{reason:'SPAM'}})).status()).toBe(201);expect((await participant.page.request.post(`/api/sessions/${sessionId}/messages/${answerMessage.id}/report`,{data:{reason:'SPAM'}})).status()).toBe(409);
    const floodStatuses:number[]=[];for(let index=0;index<5;index++)floodStatuses.push((await participant.page.request.post(`/api/sessions/${sessionId}/messages`,{data:{content:`Message rapide ${index}`,clientRequestId:crypto.randomUUID()}})).status());expect(floodStatuses).toContain(429);expect(await prisma.sessionMessage.count({where:{sessionId,author:{email:participant.email},createdAt:{gte:new Date(Date.now()-6000)}}})).toBeLessThanOrEqual(3);
    expect((await participant.page.request.delete(`/api/sessions/${sessionId}/join`)).status()).toBe(200);expect((await participant.page.request.get(`/api/sessions/${sessionId}/messages`)).status()).toBe(403);
    expect((await participant.page.request.post(`/api/sessions/${sessionId}/join`)).status()).toBe(201);expect((await owner.page.request.delete(`/api/sessions/${sessionId}/participants/${participantUser.id}`)).status()).toBe(200);expect((await participant.page.request.get(`/api/sessions/${sessionId}/messages`)).status()).toBe(403);expect((await participant.page.request.post(`/api/sessions/${sessionId}/join`)).status()).toBe(201);await participant.page.waitForTimeout(5200);const target=await participant.page.request.post(`/api/sessions/${sessionId}/messages`,{data:{content:'Message à modérer',clientRequestId:crypto.randomUUID()}});expect(target.status()).toBe(201);const targetMessage=(await target.json()).message;
    expect((await owner.page.request.delete(`/api/admin/moderation/messages/${targetMessage.id}`,{data:{reason:'Test de modération'}})).status()).toBe(200);expect((await owner.page.request.patch(`/api/admin/moderation/users/${participantUser.id}/mute`,{data:{minutes:60,reason:'Test'}})).status()).toBe(200);expect((await participant.page.request.post(`/api/sessions/${sessionId}/messages`,{data:{content:'Message bloqué',clientRequestId:crypto.randomUUID()}})).status()).toBe(403);expect(await prisma.moderationLog.count({where:{actor:{email:owner.email}}})).toBeGreaterThanOrEqual(2);
    expect((await outsider.page.request.get('/api/admin/moderation/chat')).status()).toBe(403);expect((await owner.page.request.post('/api/notifications/read-all')).status()).toBe(200);expect((await owner.page.request.get('/api/notifications').then(response=>response.json())).unreadCount).toBe(0);expect(firstMessage.author.username).toBe(participant.username);
  }finally{if(sessionId)await prisma.gameSession.deleteMany({where:{id:sessionId}});await prisma.user.deleteMany({where:{email:{in:[owner.email,participant.email,outsider.email]}}});await prisma.$disconnect();await Promise.all([ownerContext.close(),participantContext.close(),outsiderContext.close()])}
});
