import {expect,test,type BrowserContext,type Page} from '@playwright/test';
import {PrismaClient} from '@prisma/client';
test.describe.configure({timeout:60_000});

async function register(context:BrowserContext,prefix:string){const page=await context.newPage(),stamp=`${Date.now()}${Math.floor(Math.random()*10000)}`,email=`${prefix}-${stamp}@retrocoop.test`,username=`${prefix}${stamp}`.slice(0,32),password='Test-pass-2026!';await page.goto('/inscription');const question=await page.getByText(/Combien font \d+ \+ \d+/).textContent(),values=question!.match(/\d+/g)!.map(Number);await page.getByLabel('Email').fill(email);await page.getByLabel('Pseudo').fill(username);await page.getByLabel('Mot de passe').fill(password);await page.getByLabel(/Combien font/).fill(String(values[0]+values[1]));await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page).toHaveURL(/\/catalogue\?notice=registered/);return{page,email,username,password}}
async function createSession(page:Page,maximum=2){await page.goto('/sessions/nouvelle');await page.getByLabel('Jeu').pressSequentially('Streets of Rage 3');await page.getByRole('option',{name:/Streets of Rage 3/}).click();const future=new Date(Date.now()+4*86400000).toISOString().slice(0,10);await page.getByLabel('Date',{exact:true}).fill(future);await page.getByLabel('Heure',{exact:true}).fill('20:00');await page.getByLabel('Nombre maximum de joueurs').fill(String(maximum));await page.getByLabel(/Message aux participants/).fill('Rendez-vous de test');const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/sessions')&&response.request().method()==='POST');await page.getByRole('button',{name:'Publier la session'}).click();const response=await responsePromise,body=await response.json();expect(response.status()).toBe(201);return body.session.id as string}

test('deux utilisateurs : rejoindre, quitter et administration propriétaire',async({browser})=>{
  const contextA=await browser.newContext(),contextB=await browser.newContext(),a=await register(contextA,'own'),sessionId=await createSession(a.page,2);
  await expect(a.page.getByText('Vous organisez cette session.')).toBeVisible();await expect(a.page.getByRole('heading',{name:'Gérer ma session'})).toBeVisible();await expect(a.page.getByRole('button',{name:'Fermer les inscriptions'})).toBeVisible();
  const b=await register(contextB,'join');await b.page.goto(`/sessions/${sessionId}`);await b.page.getByRole('button',{name:'Rejoindre la session'}).click();await expect(b.page.getByText('Vous participez à cette session.')).toBeVisible();await expect(b.page.getByRole('heading',{name:'Participants : 2 / 2'})).toBeVisible();
  const duplicate=await b.page.request.post(`/api/sessions/${sessionId}/join`);expect(duplicate.status()).toBe(409);expect((await duplicate.json()).code).toBe('ALREADY_JOINED');
  const forbidden=await b.page.request.patch(`/api/sessions/${sessionId}`,{data:{action:'close'}});expect(forbidden.status()).toBe(403);
  await a.page.reload();await expect(a.page.getByText(b.username,{exact:true})).toBeVisible();await expect(a.page.getByText('Session complète',{exact:true})).toBeVisible();a.page.once('dialog',dialog=>dialog.accept());await a.page.getByRole('button',{name:'Retirer'}).click();await expect(a.page.getByText(`${b.username} a été retiré de la session.`)).toBeVisible();
  await b.page.reload();await b.page.getByRole('button',{name:'Rejoindre la session'}).click();await b.page.getByRole('button',{name:'Quitter la session'}).click();await expect(b.page.getByText('Vous avez quitté la session.')).toBeVisible();
  await a.page.reload();await a.page.getByRole('button',{name:'Fermer les inscriptions'}).click();await expect(a.page.getByText('Inscriptions fermées',{exact:true})).toBeVisible();let blocked=await b.page.request.post(`/api/sessions/${sessionId}/join`);expect(blocked.status()).toBe(409);expect((await blocked.json()).code).toBe('REGISTRATIONS_CLOSED');
  await a.page.getByRole('button',{name:'Rouvrir les inscriptions'}).click();await expect(a.page.getByText('Session ouverte',{exact:true})).toBeVisible();await a.page.getByText('Modifier la session').click();await a.page.getByLabel('Nombre maximal de joueurs').fill('3');await a.page.getByRole('textbox',{name:'Message'}).fill('Message modifié');await a.page.getByRole('button',{name:'Enregistrer les modifications'}).click();await expect(a.page.getByText('La session a été mise à jour.')).toBeVisible();await expect(a.page.locator('.session-message')).toHaveText('Message modifié');
  a.page.once('dialog',dialog=>dialog.accept());await a.page.getByRole('button',{name:'Annuler la session'}).click();await expect(a.page.getByText('La session a été annulée.')).toBeVisible();blocked=await b.page.request.post(`/api/sessions/${sessionId}/join`);expect(blocked.status()).toBe(409);expect((await blocked.json()).code).toBe('SESSION_CANCELLED');
  const removeForbidden=await b.page.request.delete(`/api/sessions/${sessionId}/participants/${a.username}`);expect(removeForbidden.status()).toBe(403);
  const prisma=new PrismaClient(),stored=await prisma.gameSession.findUnique({where:{id:sessionId},include:{participants:true}});expect(stored?.status).toBe('CANCELLED');expect(stored?.message).toBe('Message modifié');expect(stored?.participants.filter(item=>item.status==='JOINED')).toHaveLength(1);
  a.page.once('dialog',dialog=>dialog.accept());await a.page.getByRole('button',{name:'Supprimer la session'}).click();await expect.poll(()=>prisma.gameSession.count({where:{id:sessionId}})).toBe(0);await prisma.user.deleteMany({where:{email:{in:[a.email,b.email]}}});await prisma.$disconnect();await contextA.close();await contextB.close();
});

test('concurrence sur la dernière place et refus des états invalides',async({browser})=>{
  const ownerContext=await browser.newContext(),oneContext=await browser.newContext(),twoContext=await browser.newContext(),owner=await register(ownerContext,'cap'),sessionId=await createSession(owner.page,2),one=await register(oneContext,'racea'),two=await register(twoContext,'raceb');
  const anonymous=await browser.newContext();expect((await anonymous.request.post(`/api/sessions/${sessionId}/join`)).status()).toBe(401);expect((await owner.page.request.delete(`/api/sessions/${sessionId}/join`)).status()).toBe(409);
  const results=await Promise.all([one.page.request.post(`/api/sessions/${sessionId}/join`),two.page.request.post(`/api/sessions/${sessionId}/join`)]);expect(results.map(result=>result.status()).sort()).toEqual([201,409]);
  const prisma=new PrismaClient();expect(await prisma.sessionParticipant.count({where:{sessionId,status:'JOINED'}})).toBe(2);const joined=results[0].status()===201?one:two,failed=results[0].status()===409?one:two;expect((await failed.page.request.post(`/api/sessions/${sessionId}/join`)).status()).toBe(409);
  await joined.page.request.delete(`/api/sessions/${sessionId}/join`);expect((await failed.page.request.delete(`/api/sessions/${sessionId}/join`)).status()).toBe(409);await prisma.gameSession.update({where:{id:sessionId},data:{startsAtUtc:new Date(Date.now()-3600000),status:'OPEN'}});const past=await failed.page.request.post(`/api/sessions/${sessionId}/join`);expect(past.status()).toBe(409);expect((await past.json()).code).toBe('SESSION_PAST');await prisma.gameSession.delete({where:{id:sessionId}});
  const capacityId=await createSession(owner.page,3);expect((await one.page.request.post(`/api/sessions/${capacityId}/join`)).status()).toBe(201);expect((await two.page.request.post(`/api/sessions/${capacityId}/join`)).status()).toBe(201);const tooLow=await owner.page.request.patch(`/api/sessions/${capacityId}`,{data:{maximumPlayers:2}});expect(tooLow.status()).toBe(409);expect((await tooLow.json()).code).toBe('CAPACITY_TOO_LOW');await prisma.gameSession.delete({where:{id:capacityId}});await prisma.user.deleteMany({where:{email:{in:[owner.email,one.email,two.email]}}});await prisma.$disconnect();await Promise.all([ownerContext.close(),oneContext.close(),twoContext.close(),anonymous.close()]);
});
