import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import sharp from 'sharp';
import {BOXARTS_ROOT,CACHE_ROOT,parseBoxartFilename,SOURCE_REPOSITORY,SOURCE_URL,BoxartEntry} from '../covers/libretro';
import {loadJson,matchGame,CoverGame} from '../covers/matcher';

type GameplayImage={path:string;source:'libretro';sourceFilename:string;width:number;height:number;fileSize:number;platformVerified:boolean;sortOrder:number;importedAt:string;sha256:string;perceptualHash:string};
type StoredGame=CoverGame&{[key:string]:unknown;gameplayImages?:GameplayImage[];coverSourceFilename?:string|null};
type Options={syncOnly:boolean;dryRun:boolean;reportOnly:boolean;game?:string;limit:number;force:boolean;resume:boolean;onlyMissing:boolean};
const SNAPS_ROOT=path.join(CACHE_ROOT,'Named_Snaps');
const catalogueFile=path.resolve('data/normalized/megadrive-games.json');
const outputRoot=path.resolve('public/gameplay/megadrive');
const manifestFile=path.resolve('public/media/megadrive-media-manifest.json');
const reportsRoot=path.resolve('reports/media');
const aliasesFile=path.resolve('config/megadrive-cover-aliases.json');
const overridesFile=path.resolve('config/megadrive-gameplay-image-overrides.json');
const coverManifestFile=path.resolve('public/covers/megadrive/covers-manifest.json');

function parseOptions(argv:string[]):Options{const get=(name:string)=>argv.find(value=>value.startsWith(`--${name}=`))?.slice(name.length+3);return{syncOnly:argv.includes('--sync-only'),dryRun:argv.includes('--dry-run'),reportOnly:argv.includes('--report-only'),game:get('game'),limit:Number(get('limit')||0),force:argv.includes('--force'),resume:!argv.includes('--no-resume'),onlyMissing:!argv.includes('--all')}}
function writeJson(file:string,value:unknown){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`,'utf8');}
function escapeHtml(value:unknown){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));}
function git(args:string[]){return spawnSync('git',args,{encoding:'utf8',stdio:'pipe'});}
export function syncMediaSources(){if(!fs.existsSync(path.join(CACHE_ROOT,'.git'))){fs.mkdirSync(path.dirname(CACHE_ROOT),{recursive:true});const clone=git(['clone','--depth','1','--filter=blob:none','--sparse',SOURCE_URL,CACHE_ROOT]);if(clone.status!==0)throw new Error(`Clone Libretro impossible: ${clone.stderr.trim()}`);}else{const pull=git(['-C',CACHE_ROOT,'pull','--ff-only']);if(pull.status!==0&&!fs.existsSync(SNAPS_ROOT))throw new Error(`Mise à jour Libretro impossible et cache Named_Snaps absent: ${pull.stderr.trim()}`);}const sparse=git(['-C',CACHE_ROOT,'sparse-checkout','set','Named_Boxarts','Named_Snaps']);if(sparse.status!==0)throw new Error(`Sparse checkout impossible: ${sparse.stderr.trim()}`);if(!fs.existsSync(BOXARTS_ROOT)||!fs.existsSync(SNAPS_ROOT))throw new Error('Named_Boxarts ou Named_Snaps absent du cache.');return SNAPS_ROOT;}

async function inventorySnaps():Promise<BoxartEntry[]>{if(!fs.existsSync(SNAPS_ROOT))throw new Error('Named_Snaps absent. Lancez npm run media:sync-sources.');const files=fs.readdirSync(SNAPS_ROOT).filter(file=>file.toLowerCase().endsWith('.png')).sort((a,b)=>a.localeCompare(b,'en'));const entries:BoxartEntry[]=[];for(let index=0;index<files.length;index+=32)entries.push(...await Promise.all(files.slice(index,index+32).map(async sourceFilename=>{const sourcePath=path.join(SNAPS_ROOT,sourceFilename),parsed=parseBoxartFilename(sourceFilename),stat=fs.statSync(sourcePath);try{const metadata=await sharp(sourcePath).metadata();return{...parsed,sourcePath,width:metadata.width??null,height:metadata.height??null,sizeBytes:stat.size,validImage:metadata.format==='png'&&Boolean(metadata.width&&metadata.height)};}catch{return{...parsed,sourcePath,width:null,height:null,sizeBytes:stat.size,validImage:false};}})));return entries;}
export async function perceptualHash(input:string|Buffer){const {data}=await sharp(input).grayscale().resize(9,8,{fit:'fill'}).raw().toBuffer({resolveWithObject:true});let bits='';for(let y=0;y<8;y++)for(let x=0;x<8;x++)bits+=data[y*9+x]>data[y*9+x+1]?'1':'0';return BigInt(`0b${bits}`).toString(16).padStart(16,'0');}
export function hammingDistance(left:string,right:string){let value=BigInt(`0x${left}`)^BigInt(`0x${right}`),count=0;while(value){count+=Number(value&1n);value>>=1n;}return count;}
export async function convertGameplay(source:string,destination:string){let quality=74,buffer=await sharp(source).rotate().resize({width:720,withoutEnlargement:true}).webp({quality}).toBuffer();while(buffer.length>220*1024&&quality>50){quality-=8;buffer=await sharp(source).rotate().resize({width:720,withoutEnlargement:true}).webp({quality}).toBuffer();}const metadata=await sharp(buffer).metadata();if(metadata.format!=='webp'||!metadata.width||!metadata.height)throw new Error('Capture WebP invalide');fs.mkdirSync(path.dirname(destination),{recursive:true});const temporary=`${destination}.${process.pid}.tmp`;fs.writeFileSync(temporary,buffer);fs.renameSync(temporary,destination);return{width:metadata.width,height:metadata.height,fileSize:buffer.length,sha256:crypto.createHash('sha256').update(buffer).digest('hex'),perceptualHash:await perceptualHash(buffer)};}

export async function runGameplayPipeline(argv=process.argv.slice(2)){
  const options=parseOptions(argv);if(options.syncOnly){console.log(`Sources média synchronisées: ${syncMediaSources()}`);return;}
  const games=JSON.parse(fs.readFileSync(catalogueFile,'utf8')) as StoredGame[],entries=await inventorySnaps(),aliases=loadJson<Record<string,string[]>>(aliasesFile,{}),manual=loadJson<Record<string,{images:Array<{provider:string;sourceFilename?:string}>;reason:string}>>(overridesFile,{}),coverManifest=loadJson<{games:Array<{slug:string;sourceFilename:string;coverPath:string;source:string}>}>(coverManifestFile,{games:[]});
  const byCover=new Map(coverManifest.games.map(item=>[item.slug,item]));let selected=games.filter(game=>!options.game||game.title.toLocaleLowerCase('fr')===options.game.toLocaleLowerCase('fr'));if(options.onlyMissing&&!options.force)selected=selected.filter(game=>!(game.gameplayImages?.length));if(options.limit)selected=selected.slice(0,options.limit);
  const matched:Array<{game:StoredGame;candidate:BoxartEntry;confidence:number;method:string;reasons:string[]}>=[],missing:Array<{internalId:string;title:string;reason:string;candidates:unknown[]}>=[],ambiguous:unknown[]=[];
  for(const game of selected){const override=manual[game.slug]?.images.find(image=>image.provider==='libretro'&&image.sourceFilename);const exactName=override?.sourceFilename??byCover.get(game.slug)?.sourceFilename;let candidate=exactName?entries.find(entry=>entry.sourceFilename.toLocaleLowerCase('en')===exactName.toLocaleLowerCase('en')&&entry.validImage):undefined,confidence=1;const method=override?'override':candidate?'cover-filename':'title-match';let reasons=[candidate?'nom identique à la jaquette validée':'correspondance par titre'];if(!candidate){const result=matchGame(game,entries,aliases,{});if(result.status==='matched'&&result.candidate){candidate=result.candidate;confidence=result.confidence;reasons=result.reasons;}else{missing.push({internalId:game.slug,title:game.title,reason:result.status==='ambiguous'?'correspondance ambiguë':'aucune capture Named_Snaps fiable',candidates:result.alternatives});if(result.status==='ambiguous')ambiguous.push(result);continue;}}matched.push({game,candidate,confidence,method,reasons});}
  const imported:Array<{internalId:string;title:string;sourceFilename:string;path:string;width:number;height:number;fileSize:number;confidence:number;method:string}>=[],invalid:Array<{sourceFilename:string;reason:string}>=entries.filter(entry=>!entry.validImage).map(entry=>({sourceFilename:entry.sourceFilename,reason:'PNG illisible'})),duplicates:unknown[]=[];
  if(!options.dryRun&&!options.reportOnly){for(const item of matched){const destination=path.join(outputRoot,`${item.game.slug}-gameplay-1.webp`),publicPath=`/gameplay/megadrive/${item.game.slug}-gameplay-1.webp`;try{let details;if(options.resume&&!options.force&&fs.existsSync(destination)){const metadata=await sharp(destination).metadata();const buffer=fs.readFileSync(destination);details={width:metadata.width!,height:metadata.height!,fileSize:buffer.length,sha256:crypto.createHash('sha256').update(buffer).digest('hex'),perceptualHash:await perceptualHash(buffer)};}else details=await convertGameplay(item.candidate.sourcePath,destination);const coverPath=byCover.get(item.game.slug)?.coverPath;if(coverPath&&fs.existsSync(path.resolve('public',coverPath.replace(/^\//,'')))){const coverHash=await perceptualHash(path.resolve('public',coverPath.replace(/^\//,'')));if(hammingDistance(coverHash,details.perceptualHash)<3)throw new Error('capture trop similaire à la jaquette');}const media:GameplayImage={path:publicPath,source:'libretro',sourceFilename:item.candidate.sourceFilename,width:details.width,height:details.height,fileSize:details.fileSize,platformVerified:true,sortOrder:1,importedAt:new Date().toISOString(),sha256:details.sha256,perceptualHash:details.perceptualHash};item.game.gameplayImages=[media];imported.push({internalId:item.game.slug,title:item.game.title,sourceFilename:item.candidate.sourceFilename,path:publicPath,width:details.width,height:details.height,fileSize:details.fileSize,confidence:item.confidence,method:item.method});}catch(error){invalid.push({sourceFilename:item.candidate.sourceFilename,reason:error instanceof Error?error.message:String(error)});}}
    writeJson(catalogueFile,games);
  }
  const manifestGames=games.map(game=>({internalId:game.slug,title:game.title,cover:byCover.has(game.slug)?{path:byCover.get(game.slug)!.coverPath,source:byCover.get(game.slug)!.source,sourceFilename:byCover.get(game.slug)!.sourceFilename}:null,gameplayImages:game.gameplayImages??[]})).sort((a,b)=>a.internalId.localeCompare(b.internalId,'en'));if(!options.dryRun)writeJson(manifestFile,{generatedAt:new Date().toISOString(),sourceRepository:SOURCE_REPOSITORY,games:manifestGames});
  fs.mkdirSync(reportsRoot,{recursive:true});writeJson(path.join(reportsRoot,'gameplay-images-matched.json'),options.reportOnly?games.flatMap(game=>(game.gameplayImages??[]).map(image=>({internalId:game.slug,title:game.title,...image}))):imported);writeJson(path.join(reportsRoot,'gameplay-images-missing.json'),missing);writeJson(path.join(reportsRoot,'gameplay-images-ambiguous.json'),ambiguous);writeJson(path.join(reportsRoot,'gameplay-images-invalid.json'),invalid);writeJson(path.join(reportsRoot,'gameplay-images-duplicates.json'),duplicates);
  const counts=games.map(game=>game.gameplayImages?.length??0),images=games.flatMap(game=>game.gameplayImages??[]),summary={generatedAt:new Date().toISOString(),dryRun:options.dryRun,totalGames:games.length,sourceFiles:entries.length,selectedGames:selected.length,matched:matched.length,imported:imported.length,gamesWithAtLeastOneGameplayImage:counts.filter(count=>count>=1).length,gamesWithTwoGameplayImages:counts.filter(count=>count===2).length,gamesWithThreeGameplayImages:counts.filter(count=>count===3).length,gamesWithoutGameplayImage:counts.filter(count=>count===0).length,totalGameplayImages:images.length,libretroImages:images.filter(image=>image.source==='libretro').length,igdbImages:0,screenscraperImages:0,invalidImagesRejected:invalid.length,duplicatesRejected:duplicates.length,totalSizeBeforeOptimization:matched.reduce((sum,item)=>sum+item.candidate.sizeBytes,0),totalSizeAfterOptimization:images.reduce((sum,image)=>sum+image.fileSize,0)};writeJson(path.join(reportsRoot,'gameplay-images-summary.json'),summary);
  const cards=manifestGames.map(game=>`<article><h2>${escapeHtml(game.title)}</h2><div>${game.cover?`<img src="../../public${escapeHtml(game.cover.path)}" alt="Jaquette de ${escapeHtml(game.title)}">`:''}${game.gameplayImages.map(image=>`<img src="../../public${escapeHtml(image.path)}" alt="Capture de gameplay de ${escapeHtml(game.title)}">`).join('')}</div><p>${game.gameplayImages.map(image=>`${escapeHtml(image.sourceFilename)} · ${image.width}×${image.height} · ${Math.round(image.fileSize/1024)} Ko`).join('<br>')||'Aucune capture'}</p></article>`).join('');fs.writeFileSync(path.join(reportsRoot,'gameplay-images-review.html'),`<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Retro Coop — captures gameplay</title><style>body{font:15px system-ui;max-width:1300px;margin:2rem auto;background:#eef2f8;color:#151923}article{background:#fff;border:1px solid #ccd5e5;border-radius:10px;padding:1rem;margin:1rem}img{width:260px;max-height:230px;object-fit:contain;background:#111;margin:.3rem}</style><h1>Captures gameplay Mega Drive</h1><p>${summary.gamesWithAtLeastOneGameplayImage}/${summary.totalGames} jeux couverts.</p>${cards}`,'utf8');console.log(JSON.stringify(summary,null,2));return summary;
}
if(import.meta.url===new URL(`file://${process.argv[1].replaceAll('\\','/')}`).href)runGameplayPipeline().catch(error=>{console.error(error);process.exitCode=1;});
